### ISSUE TITLE
Request to also publish to open-vsx

### ISSUE THREAD

**Issue by brunoais** [furudean/vscode-renpy-warp#17]
Users of derivative options to `visual-studio-code` do not have access to microsoft's visual studio code marketplace. There's an alternative marketplace called [open-vsx](https://open-vsx.org/): https://open-vsx.org/

Users of `visual-studio-code` and `visual-studio-code` derivatives can use this store.

To publish to Open VSX using the workflows system, you can edit https://github.com/furudean/vscode-renpy-warp/blob/main/.github/workflows/release.yaml#L68 to include [HaaLeo's publish vs code](https://github.com/marketplace/actions/publish-vs-code-extension) premade step.

```
      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v1
        id: publishToOpenVSX
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
```

I see you use `vsce`. If you want to use a cli for it, the equivalent is [`ovsx`](https://www.npmjs.com/package/ovsx).

Most likely, the command is: `ovsx publish "renpy-warp-${{ github.ref_name }}-${{ matrix.platformName }}.vsix"`.

Thank you in advance.
